### ISSUE TITLE
TODO: Integration Test

### ISSUE THREAD

**Issue by NFiedler** [bit-bots/bitbots_behavior#94]
In this Issue, we can collect all the TODOs for an integration test of the Behavior.

- [x] Find proper values for localization precision thresholds (#72 )
- [x] Check whether the kick areas work with the current kick
- [x] Check walk in with localization for all positions
- [x] Check behavior with and without localization for each role
- [x] Check all parameters
